{
 "title": "Mavis Application",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {}
   },
   {
    "name": "log_group",
    "query": {}
   },
   {
    "name": "service",
    "query": "mavis-$environment-web,mavis-$environment-sidekiq"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Deployments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClusterName": "mavis-$environment", "ServiceName": "$service" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "System and Background Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "CPU Utilization By Task",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Utilization By Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "CPU Utilization By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Utilization By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Jobs Performed (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse message /Performed (?<job_type>[^ ]*)/\n| display @timestamp\n| filter ispresent(job_type)\n| stats count() as rate by bin(1m),job_type",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(1m)",
      "job_type"
     ]
    }
   ]
  },
  {
   "title": "Jobs Errors (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter level like /(?i)error/ \n| filter ispresent(payload.job_class)\n| stats count() as rate by bin(1m),job_class",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(1m)",
      "job_class"
     ]
    }
   ]
  },
  {
   "title": "Requests to Mavis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP status codes (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expression": "fields @timestamp, path, remote_addr, user_agent\n | sort @timestamp desc\n | filter ispresent(status)\n | stats count() as rate by bin(1m),status",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [
        "bin(1m)",
        "status"
       ]
      }
     ]
    },
    {
     "title": "Paths called (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expression": "fields @timestamp\n| filter ispresent(path)\n| parse path /(?<main_path>\\/[^\\/]*)/\n| stats count() by bin(1m),main_path",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [
        "bin(1m)",
        "main_path"
       ]
      }
     ]
    },
    {
     "title": "HTTP responses by method (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expression": "fields @timestamp\n| filter ispresent(path)\n| stats sum(method='GET') as GET,\n        sum(method='HEAD') as HEAD,\n        sum(method='OPTIONS') as OPTIONS,\n        sum(method='TRACE') as TRACE,\n        sum(method='PUT') as PUT,\n        sum(method='DELETE') as DELETE,\n        sum(method='POST') as POST,\n        sum(method='PATCH') as PATCH,\n        sum(method='CONNECT') as CONNECT\n        by bin(1m)",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [ "bin(1m)" ]
      }
     ]
    },
    {
     "title": "5XX responses by method (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expression": "fields @timestamp\n| filter ispresent(path)\n| filter status like /5/\n| stats sum(method='GET') as GET,\n        sum(method='HEAD') as HEAD,\n        sum(method='OPTIONS') as OPTIONS,\n        sum(method='TRACE') as TRACE,\n        sum(method='PUT') as PUT,\n        sum(method='DELETE') as DELETE,\n        sum(method='POST') as POST,\n        sum(method='PATCH') as PATCH,\n        sum(method='CONNECT') as CONNECT\n        by bin(1m)",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [ "bin(1m)" ]
      }
     ]
    },
    {
     "title": "5XX responses by path (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expression": "fields @timestamp\n| filter ispresent(path)\n| filter status like /5/\n| parse path /(?<main_path>\\/[^\\/]*)/\n| stats count() as rate by bin(1m),main_path",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [
        "bin(1m)",
        "main_path"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Long term behavior",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "5XX response ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expression": "filter ispresent(status)\n| stats SUM(status LIKE \"5\")/COUNT() as ratio by bin(24h)",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [ "bin(24h)" ]
      }
     ]
    },
    {
     "title": "Average request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expression": "filter ispresent(dur)\n| stats avg(dur) as ratio by bin(24h)\n| limit 10000",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [ "bin(24h)" ]
      }
     ]
    },
    {
     "title": "Response duration greater than X seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expression": "filter ispresent(dur)\n| stats sum(dur>1000)/count(dur) as duration_1s,\n        sum(dur>5000)/count(dur) as duration_5s,\n        sum(dur>10000)/count(dur) as duration_10s,\n        sum(dur>30000)/count(dur) as duration_30s,\n        sum(dur>60000)/count(dur) as duration_60s by bin(24h)",
       "logGroups": [
        { "arn": "$log_group", "name": "$log_group" }
       ],
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average",
       "statsGroups": [ "bin(24h)" ]
      }
     ]
    }
   ]
  }
 ]
}