{
 "title": "Mavis Database",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {}
   },
   {
    "name": "DBLogGroup",
    "query": "/aws/rds/cluster/mavis-$environment/postgresql"
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB Volume Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment" },
     "expression": "SELECT CPUUtilization FROM \\\"AWS/RDS\\\"",
     "metricName": "VolumeBytesUsed",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Role", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "mavis-$environment" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = 'mavis-$environment' GROUP BY Role",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ACU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "label": "ACUs",
     "metricName": "ServerlessDatabaseCapacity",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "expression": "SELECT CPUUtilization FROM \\\"AWS/RDS\\\"",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Role", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "mavis-$environment" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = 'mavis-$environment' GROUP BY Role",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Log insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Long query count (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse \"duration: * ms\" as duration_ms\n| filter duration_ms > 1000\n| stats count() by bin(5m)",
     "logGroups": [
      { "arn": "$DBLogGroup", "name": "$DBLogGroup" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Average query duration (ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse \"duration: * ms  execute *: *\" as duration_ms, command, statement\n| filter duration_ms > 1000\n| stats avg(duration_ms) as duration, count() as total by statement\n| sort duration desc\n| display duration, total, statement\n| limit 20",
     "logGroups": [
      { "arn": "$DBLogGroup", "name": "$DBLogGroup" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "statement" ]
    }
   ]
  },
  {
   "title": "Deadlock count (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like \"deadlock detected\"\n| stats count() as deadlocks by bin(5m) ",
     "logGroups": [
      { "arn": "$DBLogGroup", "name": "$DBLogGroup" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Longest individual queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse \"duration: * ms  execute *: *\" as duration_ms, command, statement\n| filter duration_ms > 1000\n| display duration_ms, statement\n| sort duration_ms desc",
     "logGroups": [
      { "arn": "$DBLogGroup", "name": "$DBLogGroup" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Errors from Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like \":ERROR:\"\n| parse @message \":ERROR: *\" as statment\n| filter statment not like \"deadlock detected\"\n| stats count() by statment, bin(5m)",
     "logGroups": [
      { "arn": "$DBLogGroup", "name": "$DBLogGroup" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "statment",
      "bin(5m)"
     ]
    }
   ]
  },
  {
   "title": "Blockers and Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "Deadlocks",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Database Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "DatabaseConnections",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "CommitThroughput",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "CommitLatency",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      },
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "WRITER" },
       "metricName": "WriteIOPS",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Replica Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment" },
       "metricName": "AuroraReplicaLag",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment" },
       "metricName": "WriteThroughput",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment" },
       "metricName": "ReadThroughput",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Read/Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      },
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "WRITER" },
       "metricName": "WriteLatency",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
       "metricName": "BufferCacheHitRatio",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "eu-west-2",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}