{
 "title": "Networking",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "loadbalancer",
    "query": {}
   },
   {
    "name": "availability_zone",
    "query": {}
   },
   {
    "name": "environment",
    "query": {}
   },
   {
    "name": "log_group",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Load balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Target Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "$availability_zone", "LoadBalancer": "$loadbalancer" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Request Count per target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "RequestCountPerTarget",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Loadbalancer Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "4XX",
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "500",
     "metricName": "HTTPCode_ELB_500_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "502",
     "metricName": "HTTPCode_ELB_502_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "503",
     "metricName": "HTTPCode_ELB_503_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "label": "504",
     "metricName": "HTTPCode_ELB_504_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Healthy/Unhealthy Host count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "label": "Healthy",
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "label": "Unhealthy",
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Target group Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "$target_group": "*", "LoadBalancer": "$loadbalancer" },
     "label": "5XX\n",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Flow logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Connection rejection ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "fields @timestamp, action\n| filter ispresent(action)\n| stats sum(action = \"REJECT\")/count() as rejection_ratio by bin(1m)",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Connections per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expression": "fields @timestamp, action\n| stats count() as connections by bin(1m)",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  }
 ]
}