name: Apply grafana configuration
run-name: Apply grafana configuration for ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - development
          - production
      git_ref_to_deploy:
        description: Git reference to deploy
        required: false
        type: string
  workflow_call:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: string
      git_ref_to_deploy:
        required: true
        type: string
permissions: {}
concurrency:
  group: apply-grafana-${{ inputs.environment }}
env:
  aws_role: ${{ inputs.environment == 'production' && 'arn:aws:iam::820242920762:role/GithubApplyGrafanaConfiguration' || 'arn:aws:iam::393416225559:role/GithubApplyGrafanaConfiguration' }}
  aws_account_id: ${{ inputs.environment == 'production' && '820242920762' || '393416225559' }}
  environment: ${{ inputs.environment }}
  git_ref_to_deploy: ${{ inputs.git_ref_to_deploy || github.ref_name }}
jobs:
  apply-grafana:
    name: Terraform apply (Grafana)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: monitoring
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
        with:
          ref: ${{ env.git_ref_to_deploy }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cabfdba3510de1431bac9dba27511d97497fc100 # v5.1.0
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: eu-west-2
      - name: Install terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.13.3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq uuid-runtime
      - name: Deploy Grafana using tf_grafana.sh
        run: |
          export TF_VAR_slack_webhook_url=${{ inputs.environment == 'production' && secrets.GRAFANA_ALERTS_SLACK_WEBHOOK || secrets.GRAFANA_TEST_ALERTS_SLACK_WEBHOOK }}
          ./tf_grafana.sh "$environment" plan --plan-file ${{ runner.temp }}/out
          ./tf_grafana.sh "$environment" apply --plan-file ${{ runner.temp }}/out
