name: Deploy monitoring stack
run-name: Deploy monitoring stack for ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - development
          - production
      git_ref_to_deploy:
        description: Git reference to deploy
        required: false
        type: string
permissions: {}
concurrency:
  group: deploy-monitoring-${{ inputs.environment }}
env:
  aws_role: ${{ inputs.environment == 'production' && 'arn:aws:iam::820242920762:role/GithubDeployMonitoring' || 'arn:aws:iam::393416225559:role/GithubDeployMonitoring' }}
  aws_account_id: ${{ inputs.environment == 'production' && '820242920762' || '393416225559' }}
  environment: ${{ inputs.environment }}
  git_ref_to_deploy: ${{ inputs.git_ref_to_deploy || github.ref_name }}
jobs:
  plan-aws:
    name: Terraform plan (AWS)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}
    defaults:
      run:
        working-directory: monitoring/aws
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
        with:
          ref: ${{ env.git_ref_to_deploy }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cabfdba3510de1431bac9dba27511d97497fc100 # v5.1.0
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: eu-west-2
      - name: Install terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.13.3
      - name: Terraform Plan
        id: plan
        run: |
          set -e
          terraform init -backend-config="env/$environment-backend.hcl" -upgrade
          terraform plan -var-file="env/$environment.tfvars" \
          -out ${{ runner.temp }}/tfplan-aws | tee ${{ runner.temp }}/tf_stdout_aws
          TF_EXIT_CODE="${PIPESTATUS[0]}"
          cat ${{ runner.temp }}/tf_stdout_aws
          if [ "$TF_EXIT_CODE" -eq 1 ]; then
              exit "$TF_EXIT_CODE"
          fi

          # Check if there are changes to apply
          if grep -q "Your infrastructure matches the configuration." ${{ runner.temp }}/tf_stdout_aws; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "No infrastructure changes detected"
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "Infrastructure changes detected"
          fi
      - name: Upload AWS plan artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.0
        with:
          name: tfplan_monitoring_aws-${{ inputs.environment }}
          path: ${{ runner.temp }}/tfplan-aws
  notify-approval-required:
    name: Notify on approval required
    runs-on: ubuntu-latest
    needs: plan-aws
    if: ${{ inputs.environment == 'production' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
      - uses: ./.github/actions/notify-approval-required
        with:
          webhook: ${{ secrets.SLACK_MAVIS_RELEASES_WEBHOOK_URL }}
  apply-aws:
    name: Terraform apply (AWS)
    runs-on: ubuntu-latest
    needs: plan-aws
    if: needs.plan-aws.outputs.has_changes == 'true'
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: monitoring/aws
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
        with:
          ref: ${{ env.git_ref_to_deploy }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cabfdba3510de1431bac9dba27511d97497fc100 # v5.1.0
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: eu-west-2
      - name: Download AWS plan artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tfplan_monitoring_aws-${{ inputs.environment }}
          path: ${{ runner.temp }}
      - name: Install terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.13.3
      - name: Apply AWS changes
        run: |
          set -e
          terraform init -backend-config="env/$environment-backend.hcl" -upgrade
          terraform apply ${{ runner.temp }}/tfplan-aws
  apply-grafana:
    name: Terraform apply (Grafana)
    needs: [plan-aws, apply-aws]
    if: always() && needs.plan-aws.result == 'success' && (needs.apply-aws.result == 'success' || needs.apply-aws.result == 'skipped')
    permissions:
      id-token: write
    uses: ./.github/workflows/apply-grafana-config.yml
    with:
      environment: ${{ inputs.environment }}
      git_ref_to_deploy: ${{ inputs.git_ref_to_deploy }}
