name: Deploy infrastructure
run-name: Deploy infrastructure for ${{ inputs.environment }}
on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: string
      git_ref_to_deploy:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - qa
          - test
          - preview
          - training
          - sandbox-alpha
          - sandbox-beta
          - performance
          - pentest
          - production
      git_ref_to_deploy:
        description: The git commit SHA to deploy.
        required: false
        type: string
permissions: {}
env:
  environment: ${{ inputs.environment }}
  git_ref_to_deploy: ${{ inputs.git_ref_to_deploy || github.ref_name }}
  aws_role: ${{ inputs.environment == 'production' && 'arn:aws:iam::820242920762:role/GithubDeployMavisAndInfrastructure' || 'arn:aws:iam::393416225559:role/GithubDeployMavisAndInfrastructure' }}
  aws_account_id: ${{ inputs.environment == 'production' && '820242920762' || '393416225559' }}
concurrency:
  group: deploy-infrastructure-${{ inputs.environment }}
defaults:
  run:
    working-directory: app
jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
        with:
          ref: ${{ env.git_ref_to_deploy }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cabfdba3510de1431bac9dba27511d97497fc100 # v5.1.0
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: eu-west-2
      - name: Install terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.0.0
        with:
          terraform_version: 1.13.3
      - name: Terraform Plan
        id: plan
        run: |
          set -e
          terraform init -backend-config="env/$environment-backend.hcl" -upgrade
          terraform plan \
          -var-file="env/$environment.tfvars" \
          -out ${{ runner.temp }}/tfplan | tee ${{ runner.temp }}/tf_stdout
          TF_EXIT_CODE="${PIPESTATUS[0]}"
          if [ "$TF_EXIT_CODE" -eq 1 ]; then
              exit "$TF_EXIT_CODE"
          fi
          ../scripts/validate_plan.sh ${{ runner.temp }}/tf_stdout
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.0
        with:
          name: tfplan_infrastructure-${{ inputs.environment }}
          path: ${{ runner.temp }}/tfplan
  notify-approval-required:
    name: Notify on approval required
    runs-on: ubuntu-latest
    needs: plan
    if: ${{ inputs.environment == 'production' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
      - uses: ./.github/actions/notify-approval-required
        with:
          webhook: ${{ secrets.SLACK_MAVIS_RELEASES_WEBHOOK_URL }}
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.1.0
        with:
          ref: ${{ env.git_ref_to_deploy }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cabfdba3510de1431bac9dba27511d97497fc100 # v5.1.0
        with:
          role-to-assume: ${{ env.aws_role }}
          aws-region: eu-west-2
      - name: Download artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: tfplan_infrastructure-${{ inputs.environment }}
          path: ${{ runner.temp }}
      - name: Install terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.0.0
        with:
          terraform_version: 1.13.3
      - name: Dummy plan to generate zip files
        run: |
          set -e
          terraform init -backend-config="env/$environment-backend.hcl" -upgrade
          terraform plan -var-file="env/$environment.tfvars" > /dev/null
      - name: Apply the changes
        run: |
          set -e
          terraform apply ${{ runner.temp }}/tfplan
